### PR TITLE
Create FizzBuzz.py

### PR DESCRIPTION
**Pull request by TSG405**
For HactoberFest 2022! :)

### CODE REVIEW

**Comment by TSG405** [comment]
Hi @tanyagupta0201 can you please merge this PR ??

**Comment by tanyagupta0201** [comment]
Kindly add date below your name in comments as per the guidelines. You may refer to main.py in Python folder.

**Comment by TSG405** [comment]
Yes, done :)

Please check @tanyagupta0201

**Comment by TSG405** [comment]
ur repo is excluded!!!! :(

**Pull request merged**
